<?php
echo "<font color= red face='Times New Roman'>";

echo "<br>";
echo "<br>";

echo "<B>";
        echo "BIODATA DATA DIRI";
echo "<br>";
echo "<br>";

echo "<table width='560' border='0'>";
  echo "<tr>";
    echo "<td width='51'>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td width='227'>";
        echo "Nama Lengkap";
        echo "</td>";
    echo "<td width='8'>";
        echo ":";
        echo "</td>";
    echo "<td width='254'>";
        echo "Adit trio Saputra";
        echo "</td>";
  echo "</tr>";

  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td>";
        echo "Nama Panggilan";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "Adit";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
       
    echo "<td>";
        echo "Tempat, Tanggal Lahir";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "Tulungagung, 19 Oktober 1998";
        echo "</td>";
  echo "</tr>";

  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td>";
        echo "Asal SMK";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "SMk Veteran 1 Tulungagung";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
       
    echo "<td>";
        echo "Alamat";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "RT/RW:04/01, Dsn.Sukorejo, Ds.Tugu, Kec.Sendang, Kab.Tulungagung";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
       
    echo "<td>";
        echo "Tinggi/ Berat";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "168/ 50";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
       
    echo "<td>";
        echo "Cita-cita";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "Pengusaha";
        echo "</td>";
  echo "</tr>";
  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td>";
        echo "Agama";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "ISLAM";
        echo "</td>";
  echo "</tr>";

  echo "<tr>";
    echo "<td>";
        echo "&nbsp;";
        echo "</td>";
    echo "<td>";
        echo "Hobi";
        echo "</td>";
    echo "<td>";
        echo ":";
        echo "</td>";
    echo "<td>";
        echo "Bersepeda";
        echo "</td>";
  echo "</tr>";
echo "</table>";
?>
